services:
  backend:
    build:
      context: ../part1/material-applications/example-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis

  frontend:
    build:
      context: ../part1/material-applications/example-frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend

  redis:
    image: redis
